name: Deploy Flask Application to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy project to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "/app/dictation-studio-service"

      - name: Build and run Docker container on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /app/dictation-studio-service
            docker build -t dictation-studio-service .
            docker stop dictation-studio-service || true
            docker rm dictation-studio-service || true
            docker run -d --name dictation-studio-service -p 4001:4001 -v ${{ secrets.UPLOADS_DIR }}:${{ secrets.UPLOADS_DIR }} -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} -e UPLOADS_DIR=${{ secrets.UPLOADS_DIR }} -e STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} -e STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }} -e STRIPE_SUCCESS_URL=${{ secrets.STRIPE_SUCCESS_URL }} -e STRIPE_CANCEL_URL=${{ secrets.STRIPE_CANCEL_URL }} dictation-studio-service
